# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36f7199eb888cb94da0d004b319c270f9765bc17a91afda3a4e18f5403e69863fa147901891f84f914e4c6e27767cab30b4fcc76af46977bce2b7feedf74a343

test:
  secret_key_base: c003f0a7a83cdffa6c2e92d06d7f8ef02ef9f5f41d4e92cc6fc85a15b29652adaeb13ef5ed13a722c1057307b7c437bfcd937314b67ca51f5bd9a58720582698

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
